use dbJardineria;

-- Ubicaciones

insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Madrid', 'Occidente', 'España', '236544');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Bogota', 'Norte', 'Colombia', '4004');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Medellin', 'Oriente', 'Colombia', '963-87');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('New York', 'Oriente', 'Estados Unidos', '37561');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Buenos Aires', 'Sur', 'Argentina', '5388502');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Paris', 'Norte', 'Francia', '2090-023');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Roma', 'Sur', 'Italia', '6150');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Caracas', 'Oriente', 'Venezuela', '0890-03');
insert into ubicaciones (ciudad, region, pais, codigoPostal) values ('Quito', 'Oriente', 'Ecuador', '023589');

-- Jefes

insert into jefes (nombreJefe, apellidoJefe) values ('Felipe', 'Nosworthy');
insert into jefes (nombreJefe, apellidoJefe) values ('Nikolos', 'Tisor');
insert into jefes (nombreJefe, apellidoJefe) values ('Tabby', 'Munnery');
insert into jefes (nombreJefe, apellidoJefe) values ('Jehu', 'Cowell');
insert into jefes (nombreJefe, apellidoJefe) values ('Maria', 'Oolahan');
insert into jefes (nombreJefe, apellidoJefe) values ('Reidar', 'Gronaller');
insert into jefes (nombreJefe, apellidoJefe) values ('Bobbi', 'Salvage');
insert into jefes (nombreJefe, apellidoJefe) values ('Kala', 'Slatford');
insert into jefes (nombreJefe, apellidoJefe) values ('Ardella', 'Pays');
insert into jefes (nombreJefe, apellidoJefe) values ('Monte', 'Pietasch');

-- Oficinas 

insert into oficinas (telefono, direccion, codigoUbicacion) values ('+7 615 166 4302', '21 Eliot Center', 4);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+20 569 284 1325', '5 Moulton Parkway', 5);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+229 240 695 2232', '42612 Kim Park', 1);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+81 236 378 7495', '21 Corscot Junction', 3);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+7 901 458 2830', '8772 Ryan Avenue', 8);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+63 113 995 4640', '50 Twin Pines Court', 3);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+86 269 884 3298', '47 High Crossing Alley', 3);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+55 629 255 9840', '80264 Vera Parkway', 6);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+86 632 799 8415', '073 Darwin Avenue', 6);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+33 183 299 5656', '7 8th Pass', 3);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+86 229 312 8560', '665 Onsgard Crossing', 4);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+57 540 580 3095', '3057 Autumn Leaf Junction', 9);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+63 237 600 9233', '0 Londonderry Park', 4);
insert into oficinas (telefono, direccion, codigoUbicacion) values ('+503 416 624 1624', '86 Dawn Lane', 6);

-- Empleados

insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Christel', 'Sigmund', null, 142, 'cruddy0@ed.gov', 10, 9, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Abrahan', 'Greenleaf', null, 181, 'adooly1@plala.or.jp', 13, 4, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Justis', 'Bottomley', null, 109, 'jhinge2@google.fr', 2, 6, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Valentia', 'Gracewood', null, 149, 'vcaccavari3@imageshack.us', 9, 7, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Adrian', 'Barkly', null, 151, 'aeynald4@weebly.com', 6, 7, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Inge', 'Spridgeon', null, 130, 'ifalk5@flavors.me', 6, 3, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Hilliard', 'Edscer', 'Harg', 114, 'hharg6@rediff.com', 3, 3, 'Técnico en riego');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Rodge', 'Lepick', null, 113, 'rplaster7@mac.com', 13, 5, 'Arboricultor');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Hendrik', 'Perulli', null, 188, 'hbeaman8@exblog.jp', 5, 3, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Phylis', 'Kingsworth', null, 188, 'pfeechum9@technorati.com', 4, 9, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Letitia', 'Perin', null, 157, 'lizachika@dedecms.com', 4, 7, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Brittney', 'Danjoie', 'Bayns', 146, 'bbaynsb@gnu.org', 14, 8, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Drucie', 'Greed', 'Devenny', 106, 'ddevennyc@sourceforge.net', 6, 2, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Jacinta', 'Yeardley', null, 137, 'jcavozzid@comsenz.com', 13, 1, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Sabra', 'Folley', 'Vickars', 134, 'svickarse@hostgator.com', 6, 3, 'Técnico en riego');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Raleigh', 'Beckworth', null, 105, 'rtomneyf@shop-pro.jp', 9, 1, 'Arboricultor');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Bank', 'Hearty', 'LLelweln', 172, 'bllelwelng@businesswire.com', 7, 9, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Jojo', 'Benion', 'Ledwitch', 107, 'jledwitchh@yolasite.com', 3, 3, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Rollie', 'Beazleigh', 'Bille', 172, 'rbillei@ucla.edu', 8, 2, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Jenica', 'Raggatt', 'Rolfini', 101, 'jrolfinij@amazon.com', 6, 5, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Debra', 'Dreus', 'Snelle', 131, 'dsnellek@guardian.co.uk', 6, 3, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Jessalyn', 'Freeburn', null, 145, 'jkippinsl@alexa.com', 8, 7, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Lotte', 'Hayler', null, 116, 'lagglionem@ihg.com', 8, 8, 'Técnico en riego');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Thia', 'Rheaume', null, 161, 'tjandln@plala.or.jp', 1, 4, 'Arboricultor');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Mattias', 'Podbury', 'Dash', 144, 'mdasho@webs.com', 3, 4, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Kerstin', 'Tapley', null, 110, 'kdoyleyp@mail.ru', 2, 9, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Rayna', 'Oseland', null, 188, 'rsanpherq@umich.edu', 12, 8, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Dennie', 'Luesley', 'Romanini', 130, 'dromaninir@washington.edu', 14, 4, 'Jardinero');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Mathilda', 'Crankshaw', 'Le Barr', 114, 'mlebarrs@goodreads.com', 8, 7, 'Paisajista');
insert into empleados (nombreEmpleado, apellido1Empleado, apellido2Empleado, extension, email, codigoOficina, codigoJefe, puesto) values ('Xenos', 'Godbehere', 'Belone', 187, 'xbelonet@biblegateway.com', 6, 5, 'Paisajista');

-- Clientes

insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Valencia Tudball', 'Valencia', 'Tudball', '+420 977 209 4506', null, '1 Blaine Court', null, 4, 4, 979.98);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Pebrook Scroggins', 'Pebrook', 'Scroggins', '+507 615 450 3833', null, '09 Express Terrace', '3769 Pankratz Alley', 7, 7, 134.13);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Fitzgerald Elnor', 'Fitzgerald', 'Elnor', '+1 207 814 0521', null, '13548 Kipling Terrace', null, 2, 3, 722.08);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Bonnee Renbold', 'Bonnee', 'Renbold', '+86 245 948 9854', null, '077 Prairieview Center', null, 6, 9, 418.02);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Charmane Prettyjohn', 'Charmane', 'Prettyjohn', '+63 243 741 1507', null, '69 Mockingbird Circle', null, 6, 14, 747.33);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Juliane Brideoke', 'Juliane', 'Brideoke', '+976 197 497 6510', null, '9370 Mifflin Trail', null, 8, 16, 158.73);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Angel Jarrard', null, null, '+62 690 509 9357', '(138) 6589979', '75922 Autumn Leaf Point', null, 3, 3, 182.88);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Caril Cassley', null, null, '+46 986 620 8687', null, '4 Shelley Center', null, 3, 23, 184.94);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Nollie Funnell', 'Nollie', 'Funnell', '+7 316 908 5462', null, '06627 Goodland Avenue', null, 3, 11, 378.87);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Tobiah Gingle', null, null, '+1 647 801 4491', '(311) 7426085', '95 International Road', '929 Leroy Court', 5, 12, 897.51);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Eugenie Spennock', null, null, '+86 854 436 6733', null, '9 Macpherson Avenue', null, 2, 22, 936.49);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Rodd Vasyutichev', null, null, '+370 227 276 7882', null, '4 Golf Parkway', null, 9, 9, 532.22);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Reed Hurleston', null, null, '+62 709 885 5742', null, '2 Troy Drive', null, 6, 3, 655.0);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Nahum Dudin', 'Nahum', 'Dudin', '+86 560 280 4344', null, '19005 Shopko Parkway', '543 Jenna Alley', 1, 8, 821.22);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Sawyer Veneur', 'Sawyer', 'Veneur', '+86 864 828 4025', null, '56163 Dexter Parkway', null, 8, 8, 333.11);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Evanne Bolens', 'Evanne', 'Bolens', '+30 513 981 0743', null, '6 Upham Drive', null, 6, 8, 529.27);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Albert Lauks', 'Albert', 'Lauks', '+967 376 188 0631', '(444) 2744880', '94 Dexter Lane', null, 2, 7, 976.25);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Donovan Dymoke', 'Donovan', 'Dymoke', '+57 110 627 1513', null, '0361 Huxley Trail', '83683 New Castle Street', 4, 30, 193.8);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Kirbee Gavozzi', 'Kirbee', 'Gavozzi', '+86 145 453 7360', '(720) 5824641', '3546 Kedzie Lane', null, 8, 13, 121.48);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Amargo Stainson', null, null, '+82 974 250 8044', null, '9 Lighthouse Bay Circle', '18 Corscot Park', 3, 19, 339.36);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Ezmeralda Morales', 'Ezmeralda', 'Morales', '+234 451 892 9367', '(190) 6711795', '97782 Comanche Terrace', null, 5, 9, 223.29);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Viv Myton', 'Viv', 'Myton', '+55 915 762 5792', null, '49453 Granby Terrace', '121 Sage Street', 6, 20, 430.57);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Chrysler Wollen', null, null, '+62 663 703 8767', '(875) 5600366', '12214 Manitowish Park', null, 2, 30, 373.14);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Noach Pickering', 'Noach', 'Pickering', '+55 413 750 8289', null, '4 East Alley', '931 Hagan Park', 7, 21, 335.94);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Reeva Devericks', 'Reeva', 'Devericks', '+30 662 837 4402', null, '9642 Sycamore Junction', '5 Green Ridge Drive', 5, 16, 839.15);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Alphard Burwood', 'Alphard', 'Burwood', '+33 387 751 1263', null, '7 Thierer Point', '9429 Larry Alley', 5, 4, 218.39);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Tucker Aherne', 'Tucker', 'Aherne', '+63 505 230 7809', '(914) 3908975', '5905 Parkside Circle', '238 Clove Hill', 4, 24, 335.77);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Ara Hinkes', 'Ara', 'Hinkes', '+86 418 765 7591', null, '3 Cherokee Pass', '95016 Hauk Place', 9, 7, 705.69);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Diena Boich', 'Diena', 'Boich', '+48 665 981 3118', null, '6204 Crownhardt Alley', null, 8, 12, 957.7);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Hermann Doornbos', 'Hermann', 'Doornbos', '+380 401 385 3493', '(709) 5897326', '32 West Trail', null, 2, 19, 664.05);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Chevalier Rudolfer', 'Chevalier', 'Rudolfer', '+7 819 540 7140', null, '7572 Center Circle', null, 8, 12, 833.97);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Erika Lias', null, null, '+235 365 905 6699', null, '47 Corben Trail', null, 5, 26, 161.93);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Mark Khristyukhin', 'Mark', 'Khristyukhin', '+505 992 372 3785', '(963) 3818445', '2135 Rigney Lane', '976 Mitchell Circle', 6, 7, 895.82);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Fonzie Aitkenhead', 'Fonzie', 'Aitkenhead', '+86 845 650 8427', null, '63889 Oriole Terrace', null, 6, 26, 853.36);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Lola Sokell', 'Lola', 'Sokell', '+254 436 566 4598', '(870) 9771900', '80 Shasta Place', '4 Butternut Lane', 8, 26, 181.59);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Miran Alabastar', 'Miran', 'Alabastar', '+62 643 974 4390', null, '934 Packers Center', null, 4, 15, 446.13);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Harley Smallshaw', 'Harley', 'Smallshaw', '+86 972 150 6120', null, '8 Buhler Terrace', null, 3, 22, 923.55);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Pia Burrass', null, null, '+63 239 450 5901', '(980) 4370108', '96609 Lake View Place', null, 6, 7, 567.91);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Cherri Trenear', 'Cherri', 'Trenear', '+46 911 195 1715', '(874) 5875993', '1 5th Street', '11823 Haas Street', 3, 10, 562.44);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Kati Sandeland', 'Kati', 'Sandeland', '+7 677 737 5294', null, '03 John Wall Way', null, 5, 12, 397.6);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Kevyn Petricek', 'Kevyn', 'Petricek', '+46 255 540 0811', '(442) 9458897', '96 Chive Place', null, 1, 7, 709.66);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Ravid Limpkin', null, null, '+86 464 715 1960', null, '75 Pepper Wood Trail', '76 Old Gate Park', 3, 21, 626.76);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Eziechiele Ethridge', 'Eziechiele', 'Ethridge', '+45 324 824 0771', '(935) 8972947', '672 Ohio Parkway', null, 1, 1, 521.15);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Uri Dymidowski', null, null, '+86 227 571 9039', null, '9357 Continental Way', '7 Lighthouse Bay Hill', 3, 16, 928.73);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Kalie Etchell', null, null, '+385 812 534 0017', null, '05376 Loftsgordon Lane', null, 7, 15, 548.98);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Donaugh Gallimore', 'Donaugh', 'Gallimore', '+995 532 382 2013', '(752) 3837777', '981 Sheridan Court', '7 Esker Trail', 2, 26, 347.2);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Priscella Livick', 'Priscella', 'Livick', '+359 847 759 6891', null, '2 Northview Drive', '500 Novick Way', 6, 1, 156.23);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Arliene O'' Mara', 'Arliene', 'O'' Mara', '+60 906 768 4988', null, '5 Hoard Crossing', null, 3, 3, 259.97);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Griz Btham', null, null, '+970 545 827 4462', '(771) 2976515', '25 Surrey Terrace', null, 3, 17, 121.15);
insert into clientes (nombreCliente, nombreContacto, apellidoContacto, telefono, fax, direccion1, direccion2, codigoUbicacion, codigoEmpleado, limiteCredito) values ('Damien Macrow', 'Damien', 'Macrow', '+1 571 858 2018', '(745) 8674321', '792 Pierstorff Hill', null, 1, 21, 642.2);

-- Pagos

insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (39, 'Tarjeta de Credito', '2010-01-30', 1435.99);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (28, 'Efectivo', '2009-11-25', 1089.37);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (29, 'Tarjeta Debito', '2009-11-20', 984.96);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (35, 'Tarjeta de Credito', '2008-09-22', 194.72);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (37, 'Efectivo', '2008-12-26', 252.78);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (45, 'Transferencia', '2009-11-01', 751.44);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (4, 'Tarjeta de Credito', '2010-03-06', 1643.38);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (14, 'Tarjeta de Credito', '2008-08-05', 1685.63);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (28, 'Tarjeta Debito', '2010-07-13', 1763.18);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (26, 'Transferencia', '2008-02-11', 1121.24);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (20, 'Efectivo', '2009-08-01', 1838.4);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (13, 'Efectivo', '2008-05-03', 862.6);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (20, 'Tarjeta de Credito', '2007-09-20', 1492.58);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (33, 'Efectivo', '2008-08-09', 1317.06);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (35, 'Tarjeta Debito', '2008-04-24', 1933.28);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (42, 'Transferencia', '2010-01-07', 1610.28);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (25, 'Transferencia', '2009-12-31', 380.39);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (16, 'Tarjeta Debito', '2009-10-01', 694.5);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (36, 'Transferencia', '2008-09-18', 909.46);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (21, 'Transferencia', '2010-05-17', 1297.76);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (5, 'Efectivo', '2008-05-29', 818.3);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (19, 'Transferencia', '2009-01-11', 1095.33);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (35, 'Tarjeta de Credito', '2010-03-17', 820.94);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (18, 'Efectivo', '2009-12-17', 980.67);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (39, 'Tarjeta Debito', '2010-07-27', 960.23);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (14, 'Transferencia', '2010-03-08', 1311.33);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (22, 'Tarjeta Debito', '2008-04-21', 1846.08);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (22, 'Transferencia', '2008-05-29', 1895.25);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (11, 'Tarjeta de Credito', '2007-10-07', 385.35);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (7, 'Transferencia', '2009-06-26', 1019.5);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (19, 'Tarjeta de Credito', '2008-10-25', 673.02);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (18, 'Efectivo', '2008-07-14', 598.18);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (48, 'Tarjeta Debito', '2009-07-05', 1851.93);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (7, 'Tarjeta de Credito', '2010-06-16', 804.99);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (26, 'Transferencia', '2008-06-22', 740.86);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (40, 'Efectivo', '2010-07-06', 244.77);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (15, 'Tarjeta Debito', '2010-04-06', 341.81);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (1, 'Tarjeta de Credito', '2008-01-06', 433.32);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (33, 'Tarjeta Debito', '2008-12-23', 912.16);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (41, 'Tarjeta Debito', '2009-12-15', 1894.09);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (8, 'Tarjeta Debito', '2008-11-28', 716.2);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (39, 'Transferencia', '2008-10-13', 1680.04);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (43, 'Tarjeta Debito', '2010-04-18', 861.96);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (5, 'Tarjeta Debito', '2008-08-31', 1728.88);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (43, 'Transferencia', '2008-07-07', 192.13);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (12, 'Transferencia', '2008-02-13', 412.56);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (8, 'Transferencia', '2008-11-14', 1353.46);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (42, 'Transferencia', '2007-12-25', 1949.97);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (38, 'Efectivo', '2010-01-06', 1908.29);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (44, 'Transferencia', '2008-10-28', 738.15);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (20, 'Tarjeta Debito', '2008-05-06', 763.29);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (13, 'Transferencia', '2008-12-09', 1049.5);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (11, 'Transferencia', '2010-06-30', 517.0);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (15, 'Efectivo', '2010-02-28', 1293.84);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (18, 'Tarjeta de Credito', '2008-04-21', 1152.03);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (47, 'Tarjeta Debito', '2010-08-27', 523.84);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (5, 'Tarjeta de Credito', '2008-05-07', 1228.96);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (15, 'Transferencia', '2009-05-23', 503.97);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (14, 'Tarjeta Debito', '2010-07-02', 311.98);
insert into pagos (codigoCliente, formaPago, fechaPago, totalPago) values (2, 'Efectivo', '2009-10-31', 1339.34);

-- Gamas

insert into gamas (gama, descripcion, urlImagen) values ('Frutales', 'libero nullam sit amet turpis', 'http://dummyimage.com/109x100.png/dddddd/000000');
insert into gamas (gama, descripcion, urlImagen) values ('Citricos', 'nulla ultrices aliquet maecenas leo odio condimentum', 'http://dummyimage.com/237x100.png/5fa2dd/ffffff');
insert into gamas (gama, descripcion, urlImagen) values ('Aromaticas', 'duis consequat dui nec nisi volutpat eleifend donec', 'http://dummyimage.com/229x100.png/cc0000/ffffff');
insert into gamas (gama, descripcion, urlImagen) values ('Flores', 'vestibulum ante ipsum primis in faucibus', 'http://dummyimage.com/178x100.png/cc0000/ffffff');
insert into gamas (gama, descripcion, urlImagen) values ('Medicinales', 'est et tempus semper est quam pharetra magna ac', 'http://dummyimage.com/248x100.png/dddddd/000000');

-- Productos

insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Carolina Desert-thorn', 5, null, 'Jardineros.mx', 'pede justo lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem id ligula suspendisse', 71, 422.69, 367.93);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Stirton''s Bryum Moss', 1, '6x1x5', 'Vivergil', 'mauris viverra diam vitae quam suspendisse potenti nullam porttitor lacus at turpis donec posuere metus vitae ipsum aliquam non', 22, 614.86, 169.45);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Yerba Porosa', 4, '8x5x9', 'Gardena', 'phasellus in felis donec semper', 16, 701.45, 711.2);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Ambiguous Ditrichum Moss', 1, '9x2x7', 'Vivergil', 'tempus sit amet sem fusce consequat nulla nisl nunc nisl duis bibendum felis sed interdum venenatis turpis enim', 54, 783.77, 963.33);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Great Coneflower', 1, '9x2x7', 'Vivergil', 'convallis eget eleifend luctus ultricies eu nibh', 19, 359.85, 761.42);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Melanelia Lichen', 3, '7x2x6', 'Jardineros.mx', 'in hac habitasse platea dictumst etiam faucibus cursus urna ut tellus nulla ut erat id mauris vulputate elementum nullam varius', 59, 267.37, 367.07);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Henicodium Moss', 3, '3x2x5', 'Herstera Garden', null, 10, 754.32, 153.89);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Rangoon Creeper', 4, '9x2x7', 'Herstera Garden', 'vestibulum rutrum rutrum neque aenean auctor gravida sem praesent id massa id', 37, 497.79, 728.47);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Bushy Knotweed', 3, '3x2x5', 'Gardena', 'lacinia eget tincidunt eget tempus vel pede morbi porttitor lorem', 57, 974.8, 391.88);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Shiny Biscuitroot', 1, null, 'Vivergil', 'sit amet erat nulla tempus vivamus in felis eu sapien cursus vestibulum', 71, 329.42, 476.19);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Lily Of The Valley Vine', 3, '9x2x7', 'Herstera Garden', 'quis tortor id nulla ultrices aliquet maecenas leo odio condimentum id luctus nec molestie sed justo pellentesque viverra pede ac', 59, 733.17, 911.38);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Rough Eyelashweed', 3, null, 'Herstera Garden', 'ut nulla sed accumsan felis ut at dolor quis odio consequat', 3, 819.57, 163.38);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Edwards Plateau Milkvetch', 3, '3x2x5', 'Gardena', 'ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel dapibus', 68, 145.03, 738.22);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Kingston Mountains Bedstraw', 2, '2x6x2', 'Vivergil', 'sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris', 47, 947.99, 833.58);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Tennessee Gladecress', 4, '6x1x5', 'Herstera Garden', 'at vulputate vitae nisl aenean lectus pellentesque eget nunc donec quis orci', 62, 513.79, 131.96);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Profuseflower Mesamint', 3, '2x6x2', 'Vivergil', 'interdum venenatis turpis enim blandit mi in porttitor pede justo eu massa donec dapibus duis at velit eu est congue', 2, 370.18, 605.75);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Arizona Bluecurls', 4, '2x6x2', 'Jardineros.mx', 'justo nec condimentum neque sapien placerat ante nulla justo aliquam quis turpis eget elit sodales', 32, 778.08, 793.74);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Longleaf False Goldeneye', 4, '3x2x5', 'Proveedores.com', null, 19, 557.97, 177.5);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Silver Cinquefoil', 4, '6x1x5', 'Herstera Garden', null, 54, 328.01, 403.48);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Turner Wildrye', 5, null, 'Vivergil', null, 14, 419.0, 913.77);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Pseudofumaria', 2, '6x1x5', 'Herstera Garden', null, 7, 405.29, 184.41);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Leskea Moss', 5, '8x5x9', 'Vivergil', 'metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae mauris viverra', 47, 465.0, 923.6);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Intermountain Bladderpod', 4, '8x5x9', 'Gardena', 'venenatis lacinia aenean sit amet justo morbi ut odio', 82, 198.71, 382.19);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Sticky Florestina', 4, '6x1x5', 'Herstera Garden', null, 86, 401.25, 889.28);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Kanawao Ke''oke''o', 4, '7x2x6', 'Gardena', null, 60, 963.95, 197.63);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Southern Fimbry', 4, null, 'Gardena', 'sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales sed tincidunt eu felis fusce', 87, 104.39, 278.76);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Biannual Lettuce', 5, null, 'Proveedores.com', 'lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum', 8, 653.09, 185.73);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Peck''s Phacelia', 1, '2x6x2', 'Jardineros.mx', 'montes nascetur ridiculus mus vivamus vestibulum sagittis', 77, 135.41, 833.27);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Kelsey''s Phlox', 3, '8x5x9', 'Gardena', 'posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in', 38, 242.33, 114.34);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Bigleaf Crownbeard', 2, '6x1x5', 'Vivergil', 'nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat convallis morbi odio odio elementum', 78, 161.45, 942.99);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Blackbead', 4, '2x6x2', 'Vivergil', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis', 43, 278.62, 338.2);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Depreault''s Snow Lichen', 1, '6x1x5', 'Jardineros.mx', null, 22, 949.14, 604.77);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Bigelow''s Tansyaster', 5, null, 'Proveedores.com', null, 21, 844.32, 323.84);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('San Benito Fritillary', 2, '6x1x5', 'Jardineros.mx', 'aliquam non mauris morbi non lectus aliquam sit amet diam in magna bibendum imperdiet nullam orci pede venenatis non sodales', 72, 598.99, 756.97);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Ellisia', 4, null, 'Vivergil', 'eget eleifend luctus ultricies eu nibh quisque id justo sit amet sapien dignissim vestibulum vestibulum ante ipsum', 48, 582.23, 724.45);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Dwarf Cinquefoil', 1, null, 'Jardineros.mx', 'ipsum primis in faucibus orci', 99, 996.54, 926.88);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Little White Bird''s-foot', 4, '3x2x5', 'Gardena', 'phasellus id sapien in sapien iaculis congue vivamus metus arcu adipiscing molestie', 2, 596.64, 510.08);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Texas Fescue', 4, '7x2x6', 'Vivergil', 'tortor quis turpis sed ante vivamus tortor duis mattis egestas', 28, 299.54, 857.98);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Arizona Honeysuckle', 5, '2x6x2', 'Herstera Garden', 'mattis nibh ligula nec sem duis aliquam convallis nunc proin at', 96, 904.79, 441.89);
insert into productos (nombreProducto, codigoGama, dimensiones, proveedor, descripcion, cantidadStock, precioVenta, precioProveedor) values ('Spreading Phlox', 5, '2x6x2', 'Proveedores.com', 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet', 70, 907.82, 884.25);

UPDATE productos 
SET precioProveedor = precioVenta - 50;

-- Pedidos

insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-11-12', '2007-06-07', '2008-07-16', 'Despachado', 'congue etiam justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus', 27);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-08-27', '2008-10-17', '2009-05-18', 'Devuelto', 'varius ut blandit non interdum in ante vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia', 40);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-01-14', '2007-10-03', '2006-11-01', 'Devuelto', 'sociis natoque penatibus et magnis', 16);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-06-16', '2008-02-29', '2009-06-06', 'Perdido', 'ullamcorper augue a suscipit nulla elit ac nulla sed vel enim sit amet nunc viverra', 37);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-10-24', '2007-07-27', '2010-05-02', 'Despachado', null, 18);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-06-07', '2008-10-02', '2009-08-17', 'Devuelto', 'consequat morbi a ipsum integer a nibh in quis justo maecenas rhoncus aliquam', 40);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-02-10', '2007-09-25', '2008-05-15', 'Devuelto', 'pellentesque eget nunc donec quis orci eget orci vehicula condimentum curabitur in libero ut massa volutpat', 34);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-06-14', '2009-03-04', '2008-01-27', 'Perdido', null, 34);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-11-26', '2007-10-02', '2007-05-18', 'Devuelto', 'lacus at turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 44);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-10-25', '2008-06-17', '2009-08-12', 'Despachado', 'integer ac neque duis bibendum morbi non quam nec dui luctus rutrum nulla tellus in', 18);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-08-10', '2007-01-15', '2009-01-30', 'Entregado', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum', 32);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-11-04', '2009-12-16', '2009-12-30', 'Perdido', 'praesent blandit lacinia erat vestibulum sed magna at nunc commodo', 9);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-12-16', '2009-11-07', '2009-03-03', 'Despachado', 'lectus in quam fringilla rhoncus mauris', 38);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-10-22', '2008-09-04', '2009-10-02', 'Entregado', null, 36);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-10-29', '2010-04-09', '2009-12-19', 'Entregado', 'in faucibus orci luctus et ultrices', 39);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-09-01', '2006-11-04', '2008-06-09', 'Devuelto', 'habitasse platea dictumst morbi vestibulum', 15);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-03-26', '2008-04-25', '2007-06-18', 'Entregado', 'justo morbi ut odio cras mi pede malesuada in imperdiet', 16);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-03-26', '2007-10-27', '2006-10-06', 'Devuelto', 'mollis molestie lorem quisque ut erat curabitur gravida nisi at nibh', 5);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-10-02', '2009-12-17', '2007-12-02', 'Entregado', null, 37);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-11-14', '2009-08-04', '2010-06-13', 'Entregado', 'non sodales sed tincidunt eu felis fusce posuere felis', 41);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-11-11', '2009-02-06', '2009-02-21', 'Entregado', 'consequat in consequat ut nulla sed accumsan felis ut at dolor quis odio consequat', 33);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-01-27', '2006-12-02', '2008-12-09', 'Devuelto', 'odio odio elementum eu interdum eu tincidunt', 6);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-01-20', '2008-12-19', '2007-07-26', 'Devuelto', 'vel sem sed sagittis nam', 6);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-05-13', '2009-02-05', '2007-12-02', 'Entregado', null, 49);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-04-11', '2009-02-04', '2009-07-17', 'Devuelto', null, 32);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2006-09-16', '2010-06-05', '2008-01-07', 'Despachado', 'morbi a ipsum integer a nibh in quis justo maecenas', 7);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-06-30', '2008-09-16', '2007-09-05', 'Perdido', null, 40);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-01-03', '2010-03-21', '2010-04-07', 'Entregado', 'at velit vivamus vel nulla eget eros elementum pellentesque', 12);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-09-21', '2010-06-03', '2007-03-20', 'Devuelto', 'odio consequat varius integer ac leo pellentesque ultrices mattis odio donec vitae nisi nam ultrices libero', 33);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-07-01', '2007-10-21', '2009-03-19', 'Perdido', 'cum sociis natoque penatibus et magnis dis parturient', 49);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-01-01', '2009-10-25', '2007-11-22', 'Perdido', 'massa id nisl venenatis lacinia aenean sit amet justo morbi', 25);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-08-02', '2009-01-20', '2007-12-15', 'Entregado', 'in congue etiam justo etiam pretium iaculis justo in hac habitasse platea', 34);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-08-03', '2007-01-14', '2008-02-27', 'Perdido', 'diam neque vestibulum eget vulputate', 12);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-03-24', '2010-09-04', '2008-06-11', 'Despachado', null, 43);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-05-26', '2007-09-08', '2009-11-13', 'Perdido', 'dignissim vestibulum vestibulum ante ipsum primis in faucibus orci luctus', 22);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-03-23', '2007-06-13', '2007-11-03', 'Perdido', 'ante ipsum primis in faucibus orci luctus et ultrices posuere cubilia curae donec pharetra magna vestibulum aliquet ultrices', 24);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-08-15', '2010-07-13', '2010-06-17', 'Entregado', 'eu est congue elementum in hac', 32);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-09-26', '2007-06-19', '2008-08-01', 'Entregado', null, 34);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-05-12', '2009-03-05', '2009-01-25', 'Despachado', 'at velit vivamus vel nulla eget eros elementum pellentesque quisque', 38);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-01-15', '2008-01-28', '2009-02-16', 'Perdido', null, 44);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-07-29', '2010-06-29', '2007-09-17', 'Devuelto', 'duis mattis egestas metus aenean fermentum donec ut mauris eget massa tempor convallis nulla neque libero convallis', 7);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-05-19', '2009-01-19', '2007-03-05', 'Perdido', null, 24);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-12-13', '2007-11-05', '2010-08-17', 'Devuelto', 'cursus id turpis integer aliquet massa id lobortis convallis tortor risus dapibus augue vel', 19);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-05-12', '2007-04-11', '2009-03-10', 'Entregado', null, 16);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-03-19', '2010-06-26', '2008-02-08', 'Perdido', 'justo etiam pretium iaculis justo in hac habitasse platea dictumst etiam faucibus cursus urna', 15);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-03-01', '2008-05-17', '2008-02-21', 'Devuelto', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere', 20);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-02-26', '2008-01-02', '2007-12-23', 'Devuelto', 'sodales scelerisque mauris sit amet eros suspendisse accumsan tortor quis turpis sed ante vivamus tortor duis mattis egestas metus', 20);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-04-17', '2007-09-14', '2007-10-14', 'Devuelto', 'at lorem integer tincidunt ante vel ipsum praesent blandit lacinia erat vestibulum sed', 48);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-09-30', '2008-05-17', '2008-10-06', 'Despachado', 'turpis donec posuere metus vitae ipsum aliquam non mauris morbi non lectus aliquam sit amet diam in magna', 38);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-02-08', '2008-02-06', '2007-12-27', 'Perdido', 'quis orci eget orci vehicula', 48);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-10-19', '2010-03-12', '2010-05-05', 'Perdido', 'volutpat erat quisque erat eros viverra eget congue', 29);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-09-11', '2009-02-13', '2009-11-10', 'Devuelto', 'luctus et ultrices posuere cubilia', 5);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-09-19', '2009-02-16', '2007-02-19', 'Despachado', 'blandit ultrices enim lorem ipsum dolor sit amet consectetuer adipiscing elit proin interdum mauris non ligula pellentesque ultrices', 43);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2006-10-26', '2009-05-02', '2008-01-05', 'Devuelto', 'nibh fusce lacus purus aliquet at feugiat non pretium quis lectus suspendisse potenti in eleifend quam', 46);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-06-20', '2009-10-18', '2006-10-28', 'Devuelto', 'dolor morbi vel lectus in quam fringilla rhoncus mauris enim leo rhoncus', 43);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-06-13', '2010-09-02', '2009-03-06', 'Devuelto', 'nisi eu orci mauris lacinia sapien quis libero nullam sit amet turpis elementum ligula vehicula', 29);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-08-14', '2010-07-10', '2008-02-12', 'Devuelto', 'tempus semper est quam pharetra magna ac consequat metus sapien ut nunc vestibulum', 18);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-09-03', '2007-11-25', '2008-02-05', 'Perdido', 'varius ut blandit non interdum in', 20);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-09-16', '2010-01-08', '2010-08-04', 'Entregado', 'at ipsum ac tellus semper interdum mauris ullamcorper purus sit amet nulla quisque arcu libero rutrum ac lobortis vel', 42);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-08-07', '2008-08-30', '2008-06-18', 'Entregado', 'viverra diam vitae quam suspendisse potenti nullam porttitor lacus at', 19);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-03-03', '2007-11-18', '2007-12-01', 'Perdido', 'in quam fringilla rhoncus mauris enim leo rhoncus sed vestibulum sit amet cursus id turpis integer aliquet', 32);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-03-24', '2009-06-03', '2009-03-28', 'Despachado', 'consectetuer eget rutrum at lorem integer tincidunt ante vel ipsum praesent blandit', 15);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-02-25', '2007-05-29', '2010-08-30', 'Devuelto', 'magna ac consequat metus sapien ut nunc vestibulum ante ipsum primis in', 31);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-04-14', '2010-03-14', '2010-08-11', 'Devuelto', 'risus praesent lectus vestibulum quam sapien varius ut blandit non interdum in ante vestibulum ante ipsum primis in', 5);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-05-20', '2007-08-09', '2008-12-28', 'Entregado', null, 8);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2009-08-02', '2008-05-23', '2009-12-30', 'Despachado', 'phasellus in felis donec semper sapien a libero nam', 32);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-09-05', '2008-06-06', '2010-04-03', 'Devuelto', 'mauris lacinia sapien quis libero nullam sit amet turpis', 32);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2007-11-16', '2007-04-09', '2009-01-23', 'Despachado', 'lacus morbi quis tortor id nulla ultrices', 34);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2010-05-15', '2007-07-11', '2008-02-10', 'Devuelto', 'consequat ut nulla sed accumsan felis ut at dolor quis', 27);
insert into pedidos (fechaPedido, fechaEsperada, fechaEntrega, estado, comentarios, codigoCliente) values ('2008-01-05', '2008-10-07', '2007-05-22', 'Despachado', 'nulla neque libero convallis eget eleifend luctus ultricies eu nibh quisque', 12);

UPDATE pedidos
SET fechaEsperada = DATE_ADD(fechaPedido, INTERVAL 5 DAY);

UPDATE pedidos
SET fechaEntrega = DATE_SUB(fechaEsperada, INTERVAL 1 DAY);

-- Detalles Pedido

insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (51, 9, 6, 42.89);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 27, 6, 50.39);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (59, 17, 8, 11.54);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (38, 23, 5, 45.74);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (37, 16, 12, 102.01);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (13, 17, 6, 38.72);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (2, 8, 3, 59.12);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (32, 26, 8, 174.97);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (32, 28, 6, 22.12);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (57, 15, 4, 130.89);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (32, 18, 11, 45.15);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (62, 16, 5, 116.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (40, 18, 3, 12.78);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (69, 12, 3, 67.46);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (17, 14, 6, 49.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (59, 12, 8, 164.82);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (49, 35, 11, 162.53);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (39, 22, 3, 122.57);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 36, 3, 194.25);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (22, 12, 15, 182.79);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (12, 5, 13, 50.39);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (6, 8, 5, 14.91);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (42, 10, 7, 51.56);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (17, 5, 8, 165.89);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (43, 14, 1, 25.35);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (34, 27, 14, 171.44);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (13, 12, 10, 166.92);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (18, 9, 9, 34.49);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (62, 35, 6, 84.67);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (7, 19, 3, 150.77);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (19, 27, 14, 103.69);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (4, 38, 4, 69.24);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (35, 40, 8, 74.36);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (52, 39, 11, 155.19);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (64, 35, 8, 74.8);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (29, 7, 13, 70.4);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 17, 1, 194.46);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (16, 8, 15, 139.51);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (21, 38, 2, 79.38);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (47, 4, 12, 173.03);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 39, 10, 43.7);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (27, 36, 12, 80.07);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (20, 40, 6, 88.25);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (40, 26, 12, 39.66);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (15, 6, 7, 59.98);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 26, 2, 197.17);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (16, 16, 14, 92.16);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (2, 32, 4, 130.02);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (38, 3, 9, 126.8);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 30, 4, 43.83);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 32, 1, 53.41);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 32, 5, 127.17);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 26, 4, 60.24);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (5, 2, 7, 132.31);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (70, 34, 6, 57.71);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (67, 22, 3, 140.31);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (55, 35, 2, 120.15);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (13, 6, 7, 132.54);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 20, 3, 41.25);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (12, 23, 13, 163.77);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (37, 3, 11, 174.24);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 24, 9, 163.56);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 32, 3, 61.52);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (70, 25, 6, 59.9);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (65, 13, 10, 145.84);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (22, 39, 3, 111.12);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 25, 4, 95.7);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (8, 29, 9, 119.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (44, 36, 8, 122.43);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (63, 16, 1, 26.9);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 32, 2, 27.68);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (65, 21, 8, 131.37);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (2, 9, 15, 182.51);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (57, 14, 8, 99.63);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (29, 4, 13, 103.37);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 20, 1, 169.8);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (64, 20, 5, 185.78);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (12, 30, 12, 120.47);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (65, 26, 9, 136.21);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (37, 29, 14, 51.5);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (8, 9, 15, 132.04);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 37, 4, 156.86);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (33, 20, 13, 111.62);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (42, 21, 12, 35.11);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (51, 28, 1, 50.97);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (66, 22, 1, 120.0);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (16, 21, 6, 150.47);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 31, 5, 22.04);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 2, 6, 165.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (4, 16, 4, 93.91);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (10, 39, 7, 121.74);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (49, 15, 3, 78.21);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (57, 16, 14, 90.38);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 38, 3, 72.34);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (51, 28, 2, 195.9);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (65, 30, 10, 89.09);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (39, 9, 9, 179.41);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (42, 27, 3, 69.71);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 25, 9, 115.98);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (49, 7, 14, 72.16);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 10, 4, 189.15);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (13, 31, 12, 185.93);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (25, 34, 6, 138.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (24, 20, 3, 104.39);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (59, 40, 5, 54.66);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (8, 32, 10, 140.26);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 20, 11, 116.11);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (10, 38, 11, 136.5);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 38, 1, 82.9);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (49, 16, 13, 126.72);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 24, 5, 17.64);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 33, 3, 75.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 15, 7, 151.21);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 17, 15, 162.05);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (24, 13, 7, 55.06);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (61, 5, 6, 73.23);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 31, 5, 195.89);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (39, 9, 8, 68.92);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 2, 5, 187.66);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (4, 7, 5, 60.51);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (63, 6, 12, 10.61);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (34, 26, 5, 155.0);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 25, 4, 59.57);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 29, 4, 65.23);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (61, 39, 6, 16.34);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 4, 15, 125.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (7, 32, 7, 96.0);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 5, 6, 20.03);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (57, 40, 10, 139.85);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (45, 19, 14, 42.37);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (56, 11, 13, 23.32);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (53, 9, 2, 27.58);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 18, 5, 171.12);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 25, 6, 127.3);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (23, 9, 2, 52.42);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (69, 1, 7, 160.73);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (7, 34, 6, 170.91);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (43, 8, 11, 69.45);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (49, 6, 9, 29.78);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 1, 4, 160.64);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (49, 35, 3, 120.56);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (55, 1, 3, 18.67);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (31, 17, 2, 27.34);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (29, 18, 5, 155.02);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (16, 38, 6, 31.15);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 39, 6, 60.65);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (21, 25, 2, 107.34);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (10, 2, 7, 189.67);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 3, 6, 87.26);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 16, 15, 83.57);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 16, 11, 99.68);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 14, 1, 35.9);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (44, 27, 5, 196.02);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (3, 25, 14, 11.53);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 16, 15, 10.38);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 19, 11, 193.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (7, 38, 7, 30.73);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (47, 40, 11, 114.98);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 6, 12, 66.74);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 18, 12, 197.73);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (21, 28, 3, 128.37);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 31, 1, 133.93);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (2, 24, 5, 11.09);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 25, 15, 68.92);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 22, 1, 131.27);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (37, 36, 5, 62.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 11, 6, 31.17);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (18, 9, 9, 77.76);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (12, 9, 3, 109.75);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (43, 27, 1, 160.46);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 25, 9, 99.53);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (63, 40, 4, 95.37);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (31, 28, 1, 95.16);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 37, 6, 92.08);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (51, 18, 4, 113.08);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (12, 2, 10, 45.52);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (7, 4, 6, 23.38);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (24, 40, 10, 142.58);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (45, 10, 6, 57.67);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (19, 7, 4, 113.33);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (38, 8, 9, 13.86);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (44, 3, 3, 135.08);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 15, 13, 161.99);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (67, 12, 4, 198.08);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 11, 8, 167.01);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (4, 7, 5, 16.86);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (22, 13, 5, 169.33);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 1, 5, 66.36);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (66, 21, 2, 33.28);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (57, 35, 13, 110.94);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (40, 29, 1, 122.43);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 20, 2, 103.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (65, 16, 4, 39.28);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (12, 11, 7, 144.49);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 35, 15, 89.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 6, 14, 154.73);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 16, 6, 123.11);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (67, 34, 10, 117.06);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 15, 7, 109.8);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (59, 7, 3, 39.5);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (33, 23, 9, 194.88);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (39, 34, 7, 124.58);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 30, 5, 192.87);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (61, 1, 14, 176.55);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (39, 11, 10, 162.91);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (42, 23, 14, 128.5);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 19, 11, 38.24);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (10, 13, 8, 182.79);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 4, 5, 26.74);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (59, 37, 15, 177.07);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (64, 1, 3, 118.73);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (56, 7, 4, 146.63);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (18, 16, 7, 147.81);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (52, 17, 3, 34.83);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 19, 11, 62.77);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (26, 8, 2, 114.84);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 32, 10, 135.93);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (35, 5, 5, 153.91);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 14, 14, 134.12);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (35, 8, 10, 116.08);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (32, 3, 9, 24.24);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (15, 23, 3, 187.83);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (54, 5, 6, 79.36);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 14, 3, 104.62);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (48, 26, 10, 77.72);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (4, 9, 2, 155.17);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (10, 20, 6, 171.29);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 35, 15, 158.39);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (9, 38, 5, 14.32);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (65, 11, 14, 56.16);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (67, 7, 14, 92.11);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (70, 2, 2, 187.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (54, 3, 6, 130.49);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 20, 3, 106.98);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (40, 30, 3, 120.89);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 31, 7, 80.14);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 12, 1, 185.69);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (41, 12, 11, 56.38);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (15, 35, 2, 80.76);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (14, 27, 10, 72.51);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (1, 25, 15, 69.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (30, 20, 11, 105.87);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (42, 27, 2, 74.1);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (68, 11, 2, 153.26);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (4, 10, 4, 149.72);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (18, 35, 4, 109.5);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 30, 7, 110.62);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 19, 9, 157.99);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (27, 29, 7, 76.54);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (17, 7, 6, 120.27);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (13, 35, 5, 148.48);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (24, 29, 11, 45.24);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (45, 1, 4, 125.59);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (11, 24, 10, 136.92);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (53, 10, 14, 106.53);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (26, 27, 13, 195.75);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 37, 2, 82.29);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 10, 2, 111.14);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (8, 37, 14, 76.4);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (9, 12, 1, 89.13);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (63, 36, 7, 120.76);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (7, 22, 8, 74.61);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (66, 36, 4, 45.64);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (64, 29, 11, 93.19);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (36, 1, 1, 129.07);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (18, 37, 13, 174.8);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (52, 17, 10, 89.79);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (57, 12, 9, 39.78);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (62, 20, 12, 173.85);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (37, 25, 8, 83.22);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (9, 12, 10, 14.1);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 1, 3, 108.57);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (5, 3, 7, 58.48);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (58, 19, 1, 96.05);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (28, 37, 3, 38.19);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 32, 5, 111.15);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (47, 22, 7, 109.06);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 10, 1, 29.27);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (5, 33, 2, 109.2);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (24, 10, 1, 149.68);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (59, 23, 7, 161.12);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (51, 2, 3, 60.39);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (61, 23, 13, 156.79);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (52, 17, 11, 35.01);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (13, 25, 12, 32.04);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (46, 16, 9, 173.28);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (56, 25, 5, 37.02);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (43, 34, 9, 47.7);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (36, 21, 7, 31.77);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (53, 13, 9, 65.77);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (52, 38, 8, 119.74);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (63, 24, 15, 47.71);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (69, 22, 9, 150.43);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (50, 22, 5, 65.29);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (60, 21, 14, 95.55);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (67, 24, 1, 14.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (43, 4, 4, 49.87);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (22, 32, 6, 101.6);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (38, 26, 5, 155.22);
insert into detallesPedido (codigoPedido, codigoProducto, cantidad, precioUnidad) values (63, 27, 13, 13.24);
